### ISSUE TITLE
Refactor TsDemuxer's `process` method

### ISSUE THREAD

**Issue by slifty** [tvkitchen/utilities#8]
#### Description
When doing an analysis of the [MpegTsDemuxer flow](https://github.com/tvkitchen/utilities/issues/6) I found a slew of potential bugs as well as a few proposed changes.

Rather than make one issue per change, I'm making this issue to capture the idea of generally refactoring it.

The refactor should include:

- [ ] Rename attributes / etc ([comment](https://github.com/tvkitchen/utilities/issues/6#issuecomment-835052875))
- [ ] Fix (or eliminate) the leftover processing logic  ([comment](https://github.com/tvkitchen/utilities/issues/6#issuecomment-835080489))
- [ ] Fix the core processing loop to prevent corrupt `ptr` state ([comment](https://github.com/tvkitchen/utilities/issues/6#issuecomment-835089295))
